#----------------------------------------------------------------------------------#
#       ____               _   _       _   _              ____                     #
#      / ___|   ___     __| | | |     (_) | | __   ___   / ___|   ___   _ __       #
#     | |  _   / _ \   / _` | | |     | | | |/ /  / _ \ | |  _   / _ \ | '_ \      #
#     | |_| | | (_) | | (_| | | |___  | | |   <  |  __/ | |_| | |  __/ | | | |     #
#      \____|  \___/   \__,_| |_____| |_| |_|\_\  \___|  \____|  \___| |_| |_|     #
#                                                                                  #
#----------------------------------------------------------------------------------#


GenBuckets:

  CobbleStone:
    Display_Name: 
    Lore:
    -
    -
    Price: 200
    Delay: 1
  
  Sand:
    Display_Name: Sand Gen Bucket
    Lore:
    -
    -
    Price: 500
    Delay: 1
  
  Obsidian:
    Display_Name: 
    Lore:
    -
    -
    Price: 2000
    Delay: 1
    