#----------------------------------------------------------------------------------#
#       ____               _   _       _   _              ____                     #
#      / ___|   ___     __| | | |     (_) | | __   ___   / ___|   ___   _ __       #
#     | |  _   / _ \   / _` | | |     | | | |/ /  / _ \ | |  _   / _ \ | '_ \      #
#     | |_| | | (_) | | (_| | | |___  | | |   <  |  __/ | |_| | |  __/ | | | |     #
#      \____|  \___/   \__,_| |_____| |_| |_|\_\  \___|  \____|  \___| |_| |_|     #
#                                                                                  #
#----------------------------------------------------------------------------------#


GenBuckets:

  CobbleStone:
  
    Vertical:
      Display_Name: &cCobbleGenBucket (Vertical)
      Lore:
      - 
      -
      Price: 200
      Enchant_Effect: false
      Delay: 1
    
    Horizontal:
      Display_Name: &cCobbleGenBucket (Horizontal)
      Lore:
      - 
      -
      Price: 200
      Enchant_Effect: false
      Delay: 1
  
  Sand:
    Display_Name: Sand Gen Bucket
    Lore:
    -
    -
    Price: 500
    Enchant_Effect: true
    Delay: 1
  
  Obsidian:
    Display_Name: Obsidian Gen Bucket
    Lore:
    -
    -
    Price: 2000
    Enchant_Effect: true
    Delay: 1
    